name: Publish release

on: 
    push:
        tags: 
            - 'v*.*.*'
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
                cache: 'npm'
            - name: installation des dépendances
              run: npm ci
            - run: npm run build --if-present
            
            # Créer une release sur GitHub
            - name: Create GitHub Release
              id: create_release
              uses: nickatnight/releases-action@v5
              if: startsWith(github.ref, 'refs/tags/')
              with:
                branch: "main"
                name: "Release"
                message: "NEW available release"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        outputs:
           ReleaseTag: ${{ steps.create_release.outputs.release_tag }}

